package org.yvl.teamforge.exception.dto;

import lombok.RequiredArgsConstructor;

@RequiredArgsConstructor
public enum StatusCode {
    UNAUTHORIZED,
    FORBIDDEN,
    BAD_REQUEST,
    EMAIL_ALREADY_EXISTS,
    INVALID_REFRESH_TOKEN,
    VALIDATION_ERROR,
    INVALID_AUTH_PRINCIPAL,
    INVALID_CREDENTIALS,
    USER_BLOCKED,
    INTERNAL_SERVER_ERROR,
    NOT_FOUND,
    ADMIN_MODIFICATION_NOT_ALLOWED,
    SKILL_ALREADY_EXISTS,
    USER_SKILL_ALREADY_EXISTS,
    INVALID_PROJECT_STATUS_TRANSITION,
    PROJECT_ARCHIVED,
    PROJECT_ROLE_NOT_BELONG_TO_PROJECT,
    PROJECT_ROLE_SKILL_ALREADY_EXISTS,
    PROJECT_ROLE_SKILL_NOT_FOUND,
    PROJECT_ROLE_NOT_OPEN,
    PROJECT_ROLE_HAS_NO_SKILLS_REQUIREMENTS,
}
